# 1. map() : appliquer une fonction pour chaque item d'un itérable

In [5]:
def my_funct(iterable):
  return iterable * 10

my_list = [12, 56, 10, 23, 8]

# map prend en paramètre (la fonction à appliquer, l'itérable sur laquelle l'appliquer)
# ici : pour chaque élément de ma liste, applique la fonction my_funct
map_list = map(my_funct, my_list)

# on le transforme en liste pour le lire
map_list = list(map_list)
print(map_list)

[120, 560, 100, 230, 80]

# 2. zip() : assembler les items d'itérables différents, par leur index

**Attention** : si les deux itérables n'ont pas le même nombre d'objet, le plus long sera tronqué

In [8]:
in_number = [1, 2, 3, 4]
in_letter = ['un', 'deux', 'trois', 'quatre']

# zip() prend en paramètres : les deux itérables à assembler
x = zip(in_number, in_letter)

# on le converti en liste pour le lire
print(list(x))

[(1, 'un'), (2, 'deux'), (3, 'trois'), (4, 'quatre')]

# 3. replace() : pour remplacer un caractère par un autre (ou l'enlever)

In [11]:
# remplacer un caractère

my_str = "the price is : 3,5€"

# je veut remplacer la virgule par un point et le signe € en $
my_str = my_str.replace(',', ".").replace('€', "$")

print(my_str)

the price is : 3.5$

# 4. join() : prend les éléments d'un itérable et les transforme en string

In [12]:
my_iter = ['Coucou', 'les', 'copains']

# entre "" le caractère qui sépare les élements de l'itérable.
# si on veut mettre un espace : " "
my_string = "-".join(my_iter)
print(my_string)

'Coucou-les-copains'

# 5. enumerate() : pour avoir l'index des éléments d'un itérable

In [20]:

# exemple avec une liste
my_list = ['un', 'deux', 'trois']

for index, value in enumerate(my_list):
  print(index, value)

print() # je met un espace pour faciliter la lecture

# exemple avec un string
my_str = '12345'
for index, value in enumerate(my_str):
  print(index, value)

0 un
1 deux
2 trois

0 1
1 2
2 3
3 4
4 5

# 6. split() : transformer un string en liste

In [28]:
my_string = "chaque mot deviendra un item de ma liste"

my_list = my_string.split()
print(my_list)

# on précise entre les () le caractère de séparation
my_string2 = 'année/jour/mois'
my_list2 = my_string2.split("/")
print(my_list2)

['chaque', 'mot', 'deviendra', 'un', 'item', 'de', 'ma', 'liste']
['année', 'jour', 'mois']

# 7. lamba : créer une fonction anonyme qui ne servira qu'une fois

In [30]:
# si je reprend mon exemple avec map()

my_list = [12, 56, 10, 23, 8]

# au lieu de créer une fonction, j'utilise lambda
map_list = map(lambda x: x*10, my_list)

# comme tout à l'heure, je transforme le résultat de map() en liste pour le lire
map_list = list(map_list)
print(map_list)

[120, 560, 100, 230, 80]

# 8. isinstance() : vérifier le type d'un objet

In [32]:
# vérifier si mon nombre est un integer
x = isinstance(12.5, int)
print(x)

False

In [34]:
# est-ce que ma variable est une instance de classe "chat"?

class Chat:
  def __init__(self, name, race, color):
    self.name = name
    self.race = race
    self.color = color 

mon_animal = Chat('minou', 'persan', 'gris')

# vérification mon_animal est_il une instance de chat?:
y = isinstance(mon_animal, Chat)
print(y)

True

# 9. count() : compter le nombre d'occurence

In [37]:
my_str12 = "les chaussettes de l'archiduchesse sont-elles sèches, archi sèches?"

count = my_str12.count("sèches")
print(count)

2

# 10. reverse() : retourner les élements en sens inverse

In [52]:
my_last_list = ['GO', 1, 2, 3]

my_last_list.reverse()

print(my_last_list)

[3, 2, 1, 'GO']